FROM node:22-slim as build
ENV NODE_ENV=production
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install -P react react-dom @types/react-dom
RUN npm install react-scripts 
RUN npm install && mv node_modules ../
COPY . ./
RUN npm run build

# Production Server NGINX
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
EXPOSE 3001
CMD ["nginx", "-g", "daemon off;"]