FROM node:lts-alpine as build
ENV NODE_ENV=development
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install -P react react-dom @types/react-dom
RUN npm install react-scripts 
RUN npm install && mv node_modules ../
COPY . ./
RUN npm run build

# Production Server NGINX
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf

RUN apk add --no-cache openssl
COPY ./certificate/openssl.cnf /etc/nginx/certificate/openssl.cnf
RUN openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -keyout /etc/nginx/certificate/ssl_certificate_key.pem -out /etc/nginx/certificate/ssl_certificate.pem  -config /etc/nginx/certificate/openssl.cnf

EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g", "daemon off;"]