FROM node:lts-alpine as build
ENV NODE_ENV=production
WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install -P -force react react-dom @types/react-dom
RUN npm install -P @faker-js/faker
RUN npm install react-scripts

RUN npm install && mv node_modules ../
COPY . ./
RUN npm run build

# production env
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3001
CMD ["nginx", "-g", "daemon off;"]