FROM node:lts-alpine
ENV NODE_ENV=development
WORKDIR /usr/src/app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install -P -force react react-dom @types/react-dom
RUN npm install @faker-js/faker --save-dev
RUN npm install && mv node_modules ../
COPY . .
EXPOSE 3001
EXPOSE 9229
RUN chown -R node /usr/src/app
USER node
CMD ["npm", "start"]
