server {
    listen 3000 ssl default_server;
    server_name _;

    ssl_certificate /etc/nginx/certificate/ssl_certificate.crt;
    ssl_certificate_key /etc/nginx/certificate/ssl_certificate.key;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 3001;
    server_name _;

    location / {
        return 301 https://$host:3000$request_uri;
    }
}
